GET http://localhost:3000/task

###


POST http://localhost:3000/task
content-type: application/json

{
  "text": "Hello"
}

#####

PUT http://localhost:3000/task/2
content-type: application/json

{
  "text": "Reis"
}

####
PATCH http://localhost:3000/task/4
content-type: application/json

{
  "text": "euu",
  "isCompleted": true
}

####

DELETE http://localhost:3000/task/2


